name = "slinked-list"
version = "1.0.0"
license = "MIT"
author = "ZUO Zhihua"
maintainer = "zuo.zhihua@qq.com"
copyright = "Copyright 2022, ZUO Zhihua"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = "sll"

[install]
library = false
